//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class avg_salaryCSVwData
    {
        public int yearstring { get; set; }
        public double dollar { get; set; }
        public int country_id { get; set; }
        public double avg_salary { get; set; }
        public System.DateTime date { get; set; }
    }
}
