//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avg_Salary
    {
        public int avg_salary_id { get; set; }
        public int country_id { get; set; }
        public string country_name { get; set; }
        public int avg_salary1 { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
