//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcelona
    {
        public int room_id { get; set; }
        public int survey_id { get; set; }
        public int host_id { get; set; }
        public string room_type { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string borough { get; set; }
        public string neighborhood { get; set; }
        public int reviews { get; set; }
        public string overall_satisfaction { get; set; }
        public int accommodates { get; set; }
        public string bedrooms { get; set; }
        public string bathrooms { get; set; }
        public string price { get; set; }
        public string minstay { get; set; }
        public string name { get; set; }
        public System.DateTime last_modified { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string location { get; set; }
    }
}
