//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTypesAvg_Salary
    {
        public string colname { get; set; }
        public string datatype { get; set; }
    }
}
