//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Uppgift3Entities : DbContext
    {
        public Uppgift3Entities()
            : base("name=Uppgift3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amsterdam> Amsterdam { get; set; }
        public virtual DbSet<Barcelona> Barcelona { get; set; }
        public virtual DbSet<Boston> Boston { get; set; }
    }
}
