//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsDWEntities : DbContext
    {
        public CarsDWEntities()
            : base("name=CarsDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avg_Salary> Avg_Salary { get; set; }
        public virtual DbSet<CarSales> CarSales { get; set; }
        public virtual DbSet<ChargingPoint> ChargingPoint { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DataTypesAvg_Salary> DataTypesAvg_Salary { get; set; }
        public virtual DbSet<DataTypesCarSales> DataTypesCarSales { get; set; }
        public virtual DbSet<DataTypesChargingPoint> DataTypesChargingPoint { get; set; }
        public virtual DbSet<DataTypesMarketEvent> DataTypesMarketEvent { get; set; }
        public virtual DbSet<GasPrice> GasPrice { get; set; }
        public virtual DbSet<MarketEvent> MarketEvent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<avg_salaryCSVwData> avg_salaryCSVwData { get; set; }
        public virtual DbSet<bensinprisCSV> bensinprisCSV { get; set; }
        public virtual DbSet<MarketEventsCSV> MarketEventsCSV { get; set; }
        public virtual DbSet<nyreg_NorgeCSV> nyreg_NorgeCSV { get; set; }
        public virtual DbSet<nyreg_SverigeCSV> nyreg_SverigeCSV { get; set; }
    }
}
