//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class nyreg_SverigeCSV
    {
        public System.DateTime Date { get; set; }
        public string Quarter { get; set; }
        public int Year { get; set; }
        public int Month_no { get; set; }
        public string Month_name_sv { get; set; }
        public int Eletricity { get; set; }
        public int Electric_hybrids { get; set; }
        public int Charge_hybrids { get; set; }
        public int Total { get; set; }
    }
}
