//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppuppgiftMMMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class nyreg_NorgeCSV
    {
        public System.DateTime Date { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string Month_name_sv { get; set; }
        public string Quarter { get; set; }
        public int Total { get; set; }
        public int Quantity_Inc_used_cars { get; set; }
        public int Import { get; set; }
        public int Quantity_Hybrid { get; set; }
        public int Quantity_Electric { get; set; }
        public int Import_Electric { get; set; }
    }
}
